services:

  ps_labyrinth.reader:
    class: Ps\LabyrinthBundle\Labyrinth\Reader
    arguments: [@ps_labyrinth.factory.tile]

  ps_labyrinth.solver:
    class: Ps\LabyrinthBundle\Labyrinth\Solver
    arguments: [@ps_labyrinth.reader]

  ps_labyrinth.factory.tile:
    class: Ps\LabyrinthBundle\Factory\TileFactory
